name: Latest blog posts
on:
  schedule:
    - cron: '*/5  * * * *' 
  workflow_dispatch:
jobs:
  update-readme-with-latest-blog-posts:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://sametcelikbicak.com/rss.xml"
